name: Build and Publish Docker Image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Build with Maven
        run: mvn clean install
      - name: Publish to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: cristianty
          password: dckr_pat_Any3kfsxgpvZmrUhfqgV7wcbs3I
          repository: cristianty/ms37-discovery
          tags: ${{github.run_number}}